# Generated by Django 3.2.3 on 2021-06-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de especie')),
                ('nombreEspecie', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('chip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Mascota')),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1)),
                ('esterilizado', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especie', verbose_name='Especie')),
            ],
        ),
    ]
