# Generated by Django 3.2.3 on 2021-06-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210614_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=2),
        ),
    ]
