# Generated by Django 3.2.3 on 2021-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mascota_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='M', max_length=6),
        ),
    ]
