# Generated by Django 3.2.3 on 2021-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210615_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='N° Chip'),
        ),
    ]
