# Generated by Django 3.2.3 on 2021-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='idEspecie',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id de especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='N° Chip'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreMascota',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre Mascota'),
        ),
    ]
